root - ERROR - main crashed. Error: name 'ata_to_influx' is not defined
root - ERROR - main crashed. Error: name 'ata_to_influx' is not defined
root - ERROR - main crashed. Error: global name 'datetime' is not defined
root - ERROR - main crashed. Error: 'NoneType' object has no attribute '__getitem__'
root - WARNING - cannot read json data
root - ERROR - main crashed. Error: HTTPConnectionPool(host='localhost', port=8086): Max retries exceeded with url: /query?q=CREATE+DATABASE+%22influx_data_mind%22&db=influx_data_mind (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x75f74130>: Failed to establish a new connection: [Errno 111] Connection refused',))
root - ERROR - main crashed. Error: HTTPConnectionPool(host='localhost', port=8086): Max retries exceeded with url: /query?q=CREATE+DATABASE+%22influx_data_mind%22&db=influx_data_mind (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x75fd00f0>: Failed to establish a new connection: [Errno 111] Connection refused',))
root - ERROR - main crashed. Error: HTTPConnectionPool(host='localhost', port=8086): Max retries exceeded with url: /query?q=CREATE+DATABASE+%22influx_data_mind%22&db=influx_data_mind (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x75f74b10>: Failed to establish a new connection: [Errno 111] Connection refused',))
root - ERROR - main crashed. Error: HTTPConnectionPool(host='localhost', port=8086): Max retries exceeded with url: /query?q=CREATE+DATABASE+%22influx_data_mind%22&db=influx_data_mind (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x75f7d170>: Failed to establish a new connection: [Errno 111] Connection refused',))
root - WARNING - cannot read json data
root - ERROR - main crashed. Error: list index out of range
root - WARNING - cannot read json data
root - ERROR - main crashed. Error: list index out of range
root - WARNING - cannot read json data
root - ERROR - main crashed. Error: list index out of range
root - WARNING - cannot read json data
root - ERROR - main crashed. Error: list index out of range
root - WARNING - cannot read json data
root - ERROR - main crashed. Error: list index out of range
root - WARNING - cannot read json data
root - ERROR - main crashed. Error: list index out of range
root - WARNING - cannot read json data
root - ERROR - main crashed. Error: list index out of range
root - WARNING - cannot read json data
root - ERROR - main crashed. Error: list index out of range
root - WARNING - cannot read json data
root - ERROR - main crashed. Error: list index out of range
root - ERROR - main crashed. Error: 'type' object has no attribute '__getitem__'
root - ERROR - main crashed. Error: global name 'char' is not defined
root - ERROR - main crashed. Error: 'int' object has no attribute '__getitem__'
root - ERROR - main crashed. Error: global name 'none' is not defined
root - WARNING - cannot read json data
root - ERROR - main crashed. Error: list index out of range
root - ERROR - main crashed. Error: 'int' object has no attribute '__getitem__'
root - ERROR - main crashed. Error: global name 'flota' is not defined
root - ERROR - main crashed. Error: global name 'flota' is not defined
root - ERROR - main crashed. Error: 400: {"error":"partial write: field type conflict: input field \"temp_out\" on measurement \"data_mind\" is type string, already exists as type float dropped=1"}
